<a href="https://colab.research.google.com/github/FadyD123/Machine-Learning-Algorithms/blob/main/Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Step 1: Import packages, functions, and classes
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

# Step 2: Get data
x = np.arange(10).reshape(-1, 1)
y = np.array([0, 1, 0, 0, 1, 1, 1, 1, 1, 1])

# Step 3: Create a model and train it
model = LogisticRegression(solver='liblinear', C=10.0, random_state=0)
model.fit(x, y)

# Step 4: Evaluate the model
p_pred = model.predict_proba(x)
y_pred = model.predict(x)
score_ = model.score(x, y)
conf_m = confusion_matrix(y, y_pred)
report = classification_report(y, y_pred)

In [33]:
import sklearn
import pandas as pd
import numpy as np
from sklearn.datasets import load_breast_cancer 

Data_C = load_breast_cancer()

x = Data_C.data

BP = pd.DataFrame(x, columns = Data_C.feature_names)

y = Data_C.target

BP['y'] = y

print(BP)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, train_size = 0.8, 
                                                    random_state = 88)

from sklearn.linear_model import LogisticRegression

print(X_train)
print(y_train)
Lr = LogisticRegression()

Lr.fit(X_train, np.transpose(y_train))

#y_pred = Lr.predict(X_test)

#from sklearn.metrics import accuracy_score

#acc = accuracy_score(y_test, y_pred)

#from sklearn.model_selection import cross_val_score

#Scores_NB = cross_val_score(Lr, x, y, cv = 10)

#Scores_NB


     mean radius  mean texture  ...  worst fractal dimension  y
0          17.99         10.38  ...                  0.11890  0
1          20.57         17.77  ...                  0.08902  0
2          19.69         21.25  ...                  0.08758  0
3          11.42         20.38  ...                  0.17300  0
4          20.29         14.34  ...                  0.07678  0
..           ...           ...  ...                      ... ..
564        21.56         22.39  ...                  0.07115  0
565        20.13         28.25  ...                  0.06637  0
566        16.60         28.08  ...                  0.07820  0
567        20.60         29.33  ...                  0.12400  0
568         7.76         24.54  ...                  0.07039  1

[569 rows x 31 columns]
[[1.351e+01 1.889e+01 8.810e+01 ... 1.453e-01 2.666e-01 7.686e-02]
 [1.194e+01 2.076e+01 7.787e+01 ... 1.155e-01 2.465e-01 9.981e-02]
 [1.285e+01 2.137e+01 8.263e+01 ... 5.601e-02 2.488e-01 8.151e-02]
 ...
 

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)